#:kivy 1.10.0

<OptionsScreen>

	name: "options"
	
	MenuBoxLayout:
					
		StorylineLabel:
			text: "Options"
			font_size: self.height*0.4
			halign: 'center'

		MenuButton:
		    text: "Theme"
		    on_release:
		        root.changeTheme()

		MainMenuButton:




<ThemesPopup>

    themesPopupLayout: themes_pop
    font_name: 'Playfair'
	foreground_color: 1,1,1,1

    MenuBoxLayout:
	    id: themes_pop